#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "O2 + X + X <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.89e+21, 'cm^5/(mol^2*s)'),
        n = -0.5,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 1,
    label = "CH4 + X <=> C.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 2,
    label = "OX + CH4 + X <=> CH3X + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+18, 'cm^5/(mol^2*s)'),
        n = 0.7,
        Ea = (42000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 3,
    label = "CH4 + X + X <=> HX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.0009,
        n = 0,
        Ea = (72000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 4,
    label = "HX + OX <=> HOX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.28e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (11200, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "HX + CH2X <=> CH3X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 6,
    label = "HOX + CH2X <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.39e+17, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (19000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 7,
    label = "HX + CHX <=> CH2X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 8,
    label = "HOX + CHX <=> OX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (4.4e+18, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (42633.2, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction\nEa raised from 42.4 to 42.6 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
Ea raised from 42.4 to 42.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 9,
    label = "CH2X + CH2X <=> CH3X + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 10,
    label = "CHX + X <=> HX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 11,
    label = "HOX + CX <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.43e+17, 'm^2/(mol*s)'),
        n = -0.312,
        Ea = (118900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 12,
    label = "CH3X + CX <=> CH2X + CHX",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (1.5e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 13,
    label = "CX + CH2X <=> CHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 14,
    label = "OX + CX <=> OCX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.7e+19, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 15,
    label = "CO + X <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.84,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 16,
    label = "HOX + CH4 + X <=> CH3X + H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 1,
        n = 0,
        Ea = (10000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 17,
    label = "OX + H2OX <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+20, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (43100, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 18,
    label = "HX + HOX <=> H2OX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.04e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (66220, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 19,
    label = "H2O + X <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.75,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 20,
    label = "H2O + X + X <=> HX + HOX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(
        A = 0.02,
        n = 0,
        Ea = (62.3442, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Adsorption_Dissociative\nEa raised from 59.0 to 62.3 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 62.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 21,
    label = "OX + OCX <=> CO2X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.7e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (117600, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 22,
    label = "HX + CO2X <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+19, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (8400, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 23,
    label = "CO2 + X <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.005,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 24,
    label = "CO + X <=> COX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (26.4446, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW\nEa raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 25,
    label = "H2 + X + X <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.046,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 26,
    label = "H2 + CX <=> CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.04,
        n = 0,
        Ea = (29700, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 27,
    label = "X + OH(D) <=> HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 28,
    label = "HOCOX + X <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.46e+20, 'm^2/(mol*s)'),
        n = -0.213,
        Ea = (54300, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 29,
    label = "H2 + X <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 30,
    label = "X + OO[Pt] <=> OX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (41.1856, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 31,
    label = "OCX + OO[Pt] <=> HOCOX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 32,
    label = "O=C[Pt] + CH2X <=> CH3X + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 33,
    label = "O=C[Pt] + OX <=> HOX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 34,
    label = "O=C[Pt] + X <=> HX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.71e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 35,
    label = "O=C[Pt] + CHX <=> CH2X + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 36,
    label = "O=C[Pt] + CX <=> OCX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 37,
    label = "HO2 + X <=> OO[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 38,
    label = "X + H <=> HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

