#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "HCO_ads + X <=> [Pt]OC=[Pt]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+14, 'm^2/(mol*s)'),
        n = 0,
        Ea = (29.288, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_DoubleBond_to_Bidentate',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_DoubleBond_to_Bidentate
""",
)

entry(
    index = 1,
    label = "CH4 + X <=> C.[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 2,
    label = "O2 + X + X <=> OX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.89e+21, 'cm^5/(mol^2*s)'),
        n = -0.5,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 3,
    label = "OX + HCO_ads <=> OCX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 4,
    label = "OX + HX <=> HOX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.28e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (11200, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 5,
    label = "formic_acid + X + X <=> HOX + HCO_ads",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.01,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 6,
    label = "OX + H2OX <=> HOX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+20, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (43100, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 7,
    label = "HOX + HX <=> H2OX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.04e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (66220, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 8,
    label = "H2O + X <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.75,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 9,
    label = "H2O + X + X <=> HOX + HX",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(
        A = 0.02,
        n = 0,
        Ea = (62.3442, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Adsorption_Dissociative\nEa raised from 59.0 to 62.3 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
Ea raised from 59.0 to 62.3 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 10,
    label = "H2 + X + X <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.046,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 11,
    label = "CO + X <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.84,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 12,
    label = "H2 + X <=> [H][H].[Pt]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 13,
    label = "OCX + OX <=> CO2X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.7e+21, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (117600, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 14,
    label = "CO2X + HX <=> OCX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+19, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (8400, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 15,
    label = "CO2 + X <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.005,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 16,
    label = "formic_acid + X <=> formic_acidX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 17,
    label = "CO + X <=> COX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (26.4446, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW\nEa raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
Ea raised from 0.0 to 26.4 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 18,
    label = "CH4 + X + X <=> CH3X + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.0009,
        n = 0,
        Ea = (72000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 19,
    label = "OX + CH4 + X <=> HOX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+18, 'cm^5/(mol^2*s)'),
        n = 0.7,
        Ea = (42000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 20,
    label = "HOX + CH4 + X <=> CH3X + H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 1,
        n = 0,
        Ea = (10000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 21,
    label = "CH2X + HX <=> CH3X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 22,
    label = "CH2X + HOX <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.39e+17, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (19000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 23,
    label = "CH2X + HCO_ads <=> OCX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "CHX + HX <=> CH2X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 25,
    label = "[Pt]OC=[Pt] <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+09, '1/s'),
        n = 0,
        Ea = (30.6815, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined]\nEuclidian distance = 0\nfamily: Surface_Bidentate_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined]
Euclidian distance = 0
family: Surface_Bidentate_Dissociation
""",
)

entry(
    index = 26,
    label = "CHX + HOX <=> CH2X + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (4.4e+18, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (42633.2, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction\nEa raised from 42.4 to 42.6 kJ/mol to match endothermicity of reaction.',
    ),
    longDesc = 
u"""
Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
Ea raised from 42.4 to 42.6 kJ/mol to match endothermicity of reaction.
""",
)

entry(
    index = 27,
    label = "CHX + HCO_ads <=> OCX + CH2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 28,
    label = "CH2X + CH2X <=> CHX + CH3X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 29,
    label = "OX + CX <=> OCX + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.7e+19, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 30,
    label = "CHX + X <=> CX + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+22, 'cm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 31,
    label = "CX + H2 <=> CH2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.04,
        n = 0,
        Ea = (29700, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Surface/CPOX_Pt/Deutschmann2006
""",
)

entry(
    index = 32,
    label = "HOX + CX <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.43e+17, 'm^2/(mol*s)'),
        n = -0.312,
        Ea = (118900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 33,
    label = "CX + HCO_ads <=> OCX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 34,
    label = "CH3X + CX <=> CH2X + CHX",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (1.5e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 35,
    label = "CH2X + CX <=> CHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

